import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { HomepageBanner } from "@/components/banner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <HomepageBanner
          imageUrl="/images/banner_1.jpg"
          title="Welcome to My Blog"
          quote="A blog about web development and programming."
        />
        <div className="pt-20">{children}</div>
      </body>
    </html>
  );
}
